name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Build Env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: npm install -g pnpm && pnpm install && npm run blog:build

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm -r publish --access public
